server:
  port: 9527
  
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: get://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
          - Path=/payment/get/**  #断言，路径相匹配的进行
       
        - id: payment_routh #payment_route 路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配后提供服务的路由地址
          predicates:
          - Path=/payment/lb/**  #断言，路径相匹配的进行
          #并且时间要在02:21:15:51:37才可以访问
#          - After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
#          - Cookie=username,sjh
#          - Header=X-Request-Id, \d+ # 请求头要有X-Request- Id属性并且值为整数的正则表达式
#          - Host=**.baidu.com
          - Method=GET
#          Between=2020-02-02T17:45 : 06.206+08: 00[Asia/Shanghai] , 2020-03-25T18: 59 :06.206+08 :00[Asia/Shanghai ]
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka